// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRyH-HM2doaW1MbqD1KYCBc9ce8_jaXYg',
    appId: '1:288697897732:web:03619da41946e3f697b651',
    messagingSenderId: '288697897732',
    projectId: 'money-tracker-pict',
    authDomain: 'money-tracker-pict.firebaseapp.com',
    storageBucket: 'money-tracker-pict.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNgFqeTg-eHm72sDM9GWHc8curfNhdlM8',
    appId: '1:288697897732:android:be14db2878bac77297b651',
    messagingSenderId: '288697897732',
    projectId: 'money-tracker-pict',
    storageBucket: 'money-tracker-pict.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhs63Brl6TjYcHVrsB0ZAKidbf_dEP6_s',
    appId: '1:288697897732:ios:53d9fc2225be5ae597b651',
    messagingSenderId: '288697897732',
    projectId: 'money-tracker-pict',
    storageBucket: 'money-tracker-pict.appspot.com',
    iosClientId: '288697897732-2vv28ti79u09bhgei9cphrjtdrrc6sp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyTracker',
  );
}
